### ISSUE TITLE
comptime changes in zig-master - zig-libxml2 update

### ISSUE THREAD

**Issue by zbynekwinkler** [ZigEmbeddedGroup/regz#100]
Currently the build fails due to this code:

```
/buildkite/builds/79e5d261aea6-1/zig-embedded-group/regz/deps/zig-libxml2/libxml2.zig:24:13: error: function called at runtime cannot return value at comptime
--
  | return "\"" ++ major ++ "." ++ minor ++ "." ++ micro ++ "\"";
```

It seems related to this change:
- https://github.com/ziglang/zig/pull/14819

`zig-libxml2` already has a fix for this in main.

**Comment by mattnite** [comment]
Haha yeah, I submitted that patch to libxml2, but haven’t gotten around to fixing regz. Will have that up today

**Comment by zbynekwinkler** [comment]
Fixed by
- #101
